FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENV NACOS_SERVER_ADDR="192.168.1.130:8848"
ENV SPRING_PROFILES_ACTIVE="docker"
ENTRYPOINT ["java", "-jar", "app.jar"]